# Generated by Django 6.1 on 2026-09-22 13:12

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post_image_path, validators=[posts.models.validate_and_resize_post_image], verbose_name='Imagem'),
        ),
    ]
