# Generated by Django 6.1 on 2026-09-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_migrate_likes_to_reactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢')], max_length=10),
        ),
    ]
