# Generated by Django 6.1 on 2026-09-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_likes_alter_postreaction_reaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢')], max_length=10),
        ),
    ]
