# Generated by Django 6.1 on 2026-09-16 20:11

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_path, validators=[users.models.validate_profile_picture], verbose_name='Foto de perfil'),
        ),
    ]
