# Generated by Django 6.1 on 2026-09-23 16:54

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.attachment_path, validators=[chat.models.validate_attachment]),
        ),
    ]
