# Generated by Django 6.1 on 2026-10-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
